# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf4d33e10e74a163140fce883be52b8a71be88de1818b21062f74e99f4b17a500cd8fc7e747dac303c523a2a7e06c8fdf2f1c2c959b1a7c637734f81bd12c904

test:
  secret_key_base: 63b68aace124c9668ded080ae2cc394616373e0b3ea054eaf2d5ca56e79d00721abb2d1bd3ac4c7bd656920f5368b1cd1a20100c076dc8eac875ea3e25f9b6d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
